### ISSUE TITLE
DCA-Mapping

### ISSUE THREAD

**Issue by Defcon0** [netzmacht/contao-form-bundle#1]
Hi @dmolineus ,

I just took a look into your bundle. It seems to be (or to be in the future) what we need.

For contao 3 we wrote a module called [https://github.com/heimrichhannot/contao-formhybrid](https://github.com/heimrichhannot/contao-formhybrid) which (besides a bunch of other functionality which we wouldn't want to migrate to a bundle...) takes a dca configuration and renders it as a form.

The main issues of the module are:

- too much code in one module -> the new bundle needs to be way more modular
- all configuration in tl_module -> problem in Contao 4.9 with InnoDB because of row size limit

So we considered writing a form mapper from dca to symfony forms and found your bundle now.

In the roadmap I can see that this feature is planned and there's also a branch for that.

Is there some time of schedule for the time horizont this feature might get implemented?

Thanks!

Ciao Defcon0

**Comment by dmolineus** [comment]
> Is there some time of schedule for the time horizont this feature might get implemented?

It's definitely on the road map of this bundle but there's no due date defined yet. Usually features are added when needed or I get engaged to implement it.

I'd be happy about a contribution. I'm also available for an engagement to implement it.

The feature branch contain the base structure for the implementation. Concrete implementations for each dca widget is still missing (implementations of the `Netzmacht\ContaoFormBundle\Form\DcaForm\FormFieldMapper` interfaces) and also a delegation routine to delegate it to the specific mapper is missing.

**Comment by Defcon0** [comment]
OK, thanks for the quick answer. I'll take into account to contribute when a time slot's available.

**Comment by dmolineus** [comment]
> OK, thanks for the quick answer. I'll take into account to contribute when a time slot's available.

Feel free to ask if any questions occur.

**Comment by Defcon0** [comment]
I'll take a look at the state so far this or next week I think.

**Comment by dmolineus** [comment]
@Defcon0 Did you make any progress here? I'll work on it soon so if you did any progress I might continue on your current state.

**Comment by Defcon0** [comment]
Unfortunately not, I didn’t have the time :-(

**Comment by dmolineus** [comment]
Closed in favor of #2 which is in a WIP state.
