### ISSUE TITLE
Dependency Symfony Validator

### ISSUE THREAD

**Issue by cboelter** [netzmacht/contao-form-bundle#3]
Hi David,

würde aus deiner Sicht etwas dagegen sprechen den Symfony-Validator in Version ^5.0 als dependency mit aufzunehmen: https://github.com/netzmacht/contao-form-bundle/blob/master/composer.json#L33?

**Comment by dmolineus** [comment]
Wenn keine Inkompatibilitäten bestehen, dann überhaupt nicht. Machst du einen PR?

**Comment by dmolineus** [comment]
Inzwischen behoben
