### ISSUE TITLE
Compatibility with Symfony FormTypes

### ISSUE THREAD

**Issue by cboelter** [netzmacht/contao-form-bundle#5]
I'm not really sure it's a problem with the bundle or a user problem. I'm using the bundle to build some forms for the backend.
All fine ... until I tried to use the `DateType` from the Symfony Forms component. If I add the following to the config `'widget'      => ['class' => 'clr w50'],` I get this error:

```An error has occurred resolving the options of the form "Symfony\Component\Form\Extension\Core\Type\DateType": The option "widget" with value array is invalid. Accepted values are: "single_text", "text", "choice".```

If I add the `text`value to the widget I get the following error:

```Warning: Illegal string offset 'class'```

For me it seems that there is a conflict between the symfony form component and this bundle in the way how the configuration is done. I played a bit with the code and I think in this function https://github.com/netzmacht/contao-form-bundle/blob/master/src/Form/Extension/WidgetClassExtension.php#L55 the option should be renamed to something like `contaoConfig`.
What do you think, am I wrong or is this a bug? :-) If it is a bug, I can provide a Pull-Request for the changes. The Pull-Request will then contain BC breaks.

**Comment by dmolineus** [comment]
Version 2.0.0 released
