### ISSUE TITLE
Using Translations for the fields

### ISSUE THREAD

**Issue by cboelter** [netzmacht/contao-form-bundle#7]
I'm not really that this is a bug or a user problem :-) ... to have translations for my fields I'm currently using stuff like this.

```php
->add(
'field',
 TextType::class,
[
  'label'        => $this->translator->trans(
      'test.form.sale_upload.promotion.0',
      [],
      'contao_test',
      'de'
    ),
....
```
If I leave the label and help options blank, the label is not rendered in the frontend. I excepted something like `field-name` as label. Is it possible to use the Fields without a label in the config and using the translator directly in the form_theme?

**Comment by dmolineus** [comment]
I did not understand your issue correctly. Usually you can setup a translation domain and the label is automatically translated. You have to pass the translation key as label then. https://symfony.com/doc/current/reference/forms/types/form.html#label-translation-parameters
