### ISSUE TITLE
Compatibility with Contao 4.13

### ISSUE THREAD

**Issue by bezin** [netzmacht/contao-form-bundle#8]
[] The Twig dependency needs to be updated to ^3.0 (Contao 4.13 requires ^3.0). 
[] `adamquaile/symfony-fieldset-bundle` is not compatible with Symfony 5 (Contao 4.13 requires ^5.4) and seems not very active anymore. Should we implement a Fieldset Type ourselves?

**Comment by bezin** [comment]
I looked into that Fieldset Bundle: In the end it comes down to a single class (the fieldset type). So we may as well consider this a part of this bundle then? License of the Fieldset Bundle is MIT.

**Comment by dmolineus** [comment]
Version 2.0.0 released.
